### ISSUE TITLE
responses react

### ISSUE THREAD

**Issue by scenzhang** [scenzhang/small#11]
components for responses

**Comment by m1010j** [comment]
- [x] When I try to post a response when I'm logged in, I get to the sign-in page, which is as desired. But then when I enter invalid credentials, I get back to the article show page. There, if I click on the response field again, I get back to the sign-in page, where the 'invalid credentials' error is rendered.

- [x] I think it'd be good if the response textarea were to get minimized after you submit the response.

- [x] It'd be good if there was a way to get back to the article from a response show.

**Comment by scenzhang** [comment]
@m1010j made fixes

**Comment by m1010j** [comment]
👍
