### ISSUE TITLE
story create

### ISSUE THREAD

**Issue by scenzhang** [scenzhang/small#24]
api and components

**Comment by m1010j** [comment]
Make sure to render some errors the user tries to submit an empty story or a story without a title.

**Comment by scenzhang** [comment]
@m1010j just made a change to disable the submit button if title or body are empty. this is similar to what medium does. (their submit button is actually in the navbar and has a dropdown to add tags or tell you to have a title/body, but no errors are rendered on the main page. I'll add this once I start implementing the navbar user dropdown)
