### ISSUE TITLE
stories styling

### ISSUE THREAD

**Issue by scenzhang** [scenzhang/small#9]

**Comment by scenzhang** [comment]
@m1010j this is mostly just to show the article preview box and article show styling. the index will eventually be grid-like once I implement the personalized feed and group articles by author/topic, but I didn't want to spend time on the grid now before I know what that will look like

**Comment by m1010j** [comment]
The article preview box looks pretty good. But both it and the article show could use some more styling to look more like the real thing.

**Comment by scenzhang** [comment]
@m1010j made some tweaks. a lot of the differences are user features which I haven't implemented yet, do you have any specific suggestions for more changes I could make, in the absence of those features?

**Comment by m1010j** [comment]
Looks great for now!
